# Generated by Django 2.2.6 on 2020-07-27 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateOfPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfPost', models.DateTimeField()),
                ('occurrences', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('message', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threads', models.IntegerField(default=0)),
                ('totalComments', models.IntegerField(default=0)),
                ('wordPairs', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=101)),
                ('occurrences', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-occurrences'],
            },
        ),
        migrations.CreateModel(
            name='WordDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closeDistance', models.IntegerField(default=0)),
                ('shortDistance', models.IntegerField(default=0)),
                ('mediumDistance', models.IntegerField(default=0)),
                ('longDistance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WordRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrences', models.IntegerField(default=0)),
                ('inComment', models.IntegerField(default=0)),
                ('word1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word1', to='api.Word')),
                ('word2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word2', to='api.Word')),
                ('wordDistance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.WordDistance')),
            ],
            options={
                'ordering': ['-occurrences'],
            },
        ),
        migrations.CreateModel(
            name='NicknameOfPoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('numberOfPosts', models.IntegerField(default=0)),
                ('wordRelation', models.ManyToManyField(to='api.WordRelation')),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('occurrences', models.IntegerField(default=0)),
                ('subforum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.WordRelation')),
            ],
        ),
    ]
