# Generated by Django 2.2.6 on 2020-01-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200121_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordrelation',
            name='wordDistance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.WordDistance'),
        ),
    ]
